# These are supported funding model platforms

# github: zhangjh
# patreon: zhangjh
# open_collective: zhangjh
# ko_fi: zhangjh
# tidelift: npm/favlinks
# community_bridge: favlinks
# liberapay: zhangjh
# issuehunt: zhangjh
# otechie: zhangjh
custom: https://favlink.cn/img/zf.jpg
